### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by Z3r0-K0ol** [LordVader9988/secret-hitler#3]
i mean like
why?

**Comment by LordVader9988** [comment]
Just in case coz ever needed to shut down his for a time, and people needed something. I have not advertised and I still retain coz credit as developer. This is a current unneeded option, correct. @Z3r0-K0ol thanks for asking. Appreciate the call to question based on previous actions but this is not the same. Peace until thee. :)

**Comment by LordVader9988** [comment]
Also this option does help test my skills with coding and development as I'm trying to learn. Since it was in read me I wanted to replicate how production mode actually works not to compete but to learn ratger. If that makes sense. Coz does phenomenal job in making all aspects of his work user friendly so I'm using his resources to learn myself from different angles. I'd be happy to talk more if a problem arises. Plus cardbacks and stats don't work anyway ;)
